robot: "b2"  # Robot name, "go1", "go2", "b2", "b2w", "h1"
robot_scene: "empty.xml" # "scene_terrain.xml" # Robot scene 

domain_id: 1  # Domain id
interface: "enp5s0" # Interface 

use_joystick: 0 # Simulate Unitree WirelessController using a gamepad
joystick_type: "xbox" # support "xbox" and "switch" gamepad layout
joystick_device: "/dev/input/js0" # Device path
joystick_bits: 16 # Some game controllers may only have 8-bit accuracy

print_scene_information: 1 # Print link, joint and sensors information of robot

enable_elastic_band: 0 # Virtual spring band, used for lifting h1
